language: python
sudo: false
matrix:
  include:
  - python: pypy
    env: TOX_ENV=pypy
  - python: '2.7'
    env: TOX_ENV=py27
  - python: '3.6'
    env: TOX_ENV=py36,import-order,flake8
cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox
install:
- pip install tox coveralls
script:
- tox -e $TOX_ENV -- --cov=graphene_bottle
after_success:
- coveralls
